### ISSUE TITLE
Incomplete error-checking when resolving images leading to nil-context panic

### ISSUE THREAD

**Issue by Jberlinsky** [GoogleCloudPlatform/terraform-google-conversion#764]
IHAC encountering https://github.com/GoogleCloudPlatform/terraform-validator/issues/113. This debugging is in furtherance of getting that issue resolved. I'm working on getting an escalation request filed.

When I merge https://github.com/GoogleCloudPlatform/terraform-validator/pull/119 into `terraform-validator`'s `main` branch and run its tests, I receive the following stack trace:

```
--- FAIL: TestReadPlannedAssetsCoverage (0.02s)
    --- FAIL: TestReadPlannedAssetsCoverage/example_compute_disk_empty (0.02s)
panic: nil context [recovered]
	panic: nil context

goroutine 57 [running]:
testing.tRunner.func1.2(0x403f400, 0x4d93e90)
	/usr/local/Cellar/go/1.16.6/libexec/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000288f00)
	/usr/local/Cellar/go/1.16.6/libexec/src/testing/testing.go:1146 +0x4b6
panic(0x403f400, 0x4d93e90)
	/usr/local/Cellar/go/1.16.6/libexec/src/runtime/panic.go:965 +0x1b9
net/http.(*Request).WithContext(...)
	/usr/local/Cellar/go/1.16.6/libexec/src/net/http/request.go:356
golang.org/x/net/context/ctxhttp.Do(0x0, 0x0, 0x636b720, 0xc000140400, 0x406b560, 0x1, 0xc0021a8580)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/net@v0.0.0-20210503060351-7fd8e65b6420/context/ctxhttp/ctxhttp.go:27 +0x34f
golang.org/x/oauth2/internal.doTokenRoundTrip(0x0, 0x0, 0xc000140400, 0x48, 0xc0001dbdd0, 0x18)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/internal/token.go:232 +0x7b
golang.org/x/oauth2/internal.RetrieveToken(0x0, 0x0, 0xc0007227d0, 0x48, 0xc0001dbdd0, 0x18, 0x484c1d7, 0x23, 0xc002110690, 0x1, ...)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/internal/token.go:202 +0xe9
golang.org/x/oauth2.retrieveToken(0x0, 0x0, 0xc000310690, 0xc002110690, 0xc002110760, 0x403f400, 0xc002110698)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/token.go:157 +0x92
golang.org/x/oauth2.(*tokenRefresher).Token(0xc001e9fad0, 0x100f93b, 0x8, 0x203000)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/oauth2.go:270 +0x1e5
golang.org/x/oauth2.(*reuseTokenSource).Token(0xc000dfb6c0, 0x0, 0x0, 0x0)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/oauth2.go:304 +0xaf
golang.org/x/oauth2.(*Transport).RoundTrip(0xc000dfb700, 0xc000140100, 0x0, 0x0, 0x0)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/transport.go:45 +0x9e
net/http.send(0xc000140100, 0x4de4b60, 0xc000dfb700, 0x0, 0x0, 0x0, 0xc0006e2f60, 0xc002110be8, 0x1, 0x0)
	/usr/local/Cellar/go/1.16.6/libexec/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xc001e9fb60, 0xc000140100, 0x0, 0x0, 0x0, 0xc0006e2f60, 0x0, 0x1, 0x0)
	/usr/local/Cellar/go/1.16.6/libexec/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xc001e9fb60, 0xc000140100, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.16.6/libexec/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	/usr/local/Cellar/go/1.16.6/libexec/src/net/http/client.go:585
google.golang.org/api/internal/gensupport.SendRequest(0x0, 0x0, 0xc001e9fb60, 0xc000140100, 0xc002110f78, 0x55, 0x0)
	/Users/berlinsky/src/go/pkg/mod/google.golang.org/api@v0.46.0/internal/gensupport/send.go:26 +0xd0
google.golang.org/api/compute/v1.(*ImagesGetFromFamilyCall).doRequest(0xc0021110e8, 0x47ebfa7, 0x4, 0x0, 0x1010098, 0x30)
	/Users/berlinsky/src/go/pkg/mod/google.golang.org/api@v0.46.0/compute/v1/compute-gen.go:74226 +0x809
google.golang.org/api/compute/v1.(*ImagesGetFromFamilyCall).Do(0xc0021110e8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/berlinsky/src/go/pkg/mod/google.golang.org/api@v0.46.0/compute/v1/compute-gen.go:74238 +0xa5
github.com/GoogleCloudPlatform/terraform-google-conversion/google.resolveImageFamilyExists(0xc00030f200, 0x47ee6c1, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/berlinsky/src/clients/google/usb/terraform-google-conversion/google/image.go:63 +0x10a
github.com/GoogleCloudPlatform/terraform-google-conversion/google.resolveImage(0xc00030f200, 0x47ee6c1, 0x6, 0x0, 0x0, 0x0, 0x0, 0x9, 0xc0007f0d00, 0x34, ...)
	/Users/berlinsky/src/clients/google/usb/terraform-google-conversion/google/image.go:189 +0x17d2
github.com/GoogleCloudPlatform/terraform-google-conversion/google.resourceComputeDiskEncoder(0x4e81758, 0xc002031ad0, 0x47a3780, 0xc00030f200, 0xc002031b90, 0x1, 0x0, 0x0)
	/Users/berlinsky/src/clients/google/usb/terraform-google-conversion/google/compute_disk.go:373 +0x5b4
```

It appears that we reach [google/image.go line 48](https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/master/google/image.go#L48), which attempts to make a request containing an empty string `name`, which leads to a `panic`.

I'm not familiar with how modular-magician generates this file, so I'm afraid my debugging might cease to be useful beyond this point.

**Comment by melinath** [comment]
This repository is not intended to have issues filed against it - sorry for the confusion. Please add any details to the terraform-validator issue.
